name: Upload Artifact

on:
    release:
        types: [published]

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.3.2
            - uses: actions/setup-java@v1
              with:
                  java-version: '11.x'
            -   name: Set artifact version
                run: ./mvnw versions:set -DnewVersion="${{ github.event.release.tag_name }}"
            - name: Build the artifact
              run: |
                  chmod +x mvnw
                  ./mvnw -ntp clean package
            - name: Get name of the artifact
              run: |
                  ARTIFACT_PATHNAME=$(ls target/*.jar | head -n 1)
                  ARTIFACT_NAME=$(basename $ARTIFACT_PATHNAME)
                  echo ::set-env name=ARTIFACT_NAME::${ARTIFACT_NAME}
                  echo ::set-env name=ARTIFACT_PATHNAME::${ARTIFACT_PATHNAME}
            - name: Upload the artifact
              id: upload-native-executable
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ github.event.release.upload_url }}
                  asset_path: ${{ env.ARTIFACT_PATHNAME }}
                  asset_name: ${{ env.ARTIFACT_NAME }}
                  asset_content_type: application/java-archive
